### ISSUE TITLE
Copy button does not work 

### ISSUE THREAD

**Issue by marlowleon** [maschhoff/clipy#1]
Copy button does not work - After entering text and hitting clip it, the 
![image](https://github.com/maschhoff/clipy/assets/125103173/b2124f93-523e-4aa8-bffd-5076c56b2ece)

The button to copy linked save does not work (on a windows pc) and the text on the other device (iPhone) when using the QR code does not copy with the copy button.

**Comment by maschhoff** [comment]
Thanks for reporting the issue - I changed something because it doesnt use the right url. 
Can you test it with https://cmais.de/c/ or https://cmais.de/s/ - if it still doesnt work I have to rewrite the buttons logic.

**Comment by marlowleon** [comment]
With the 2 test sites provided, the feature does work on those 2 urls

**Comment by maschhoff** [comment]
okay, than please try to update your docker or pull the latest release. cheers
